language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
script:
    - pip install "notebook>=4.0,<5.0"
    - jupyter notebook --generate-config
    - python setup.py sdist
    - pip install --no-use-wheel dist/*.tar.gz

notifications:
    email:
        on_success: change
        on_failure: always
    slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4
